import { useEffect, useMemo, useRef, useState } from 'react'

type StudioTrack = {
  id: string
  name: string
  file: File
  objectUrl: string
  durationSec: number
  volume: number
  pan: number
  muted: boolean
  solo: boolean
}

type WordSync = {
  id: string
  text: string
  startSec: number
  endSec: number
}

type ChordSync = {
  id: string
  symbol: string
  timeSec: number
}

type LyricLine = {
  id: string
  startSec: number
  endSec: number
  words: WordSync[]
  chords: ChordSync[]
}

type GeneratedChart = {
  lines: LyricLine[]
  statusMessage: string
}

type NodeBundle = {
  source: AudioBufferSourceNode
  gain: GainNode
  panner: StereoPannerNode
}

const SHARP_NOTES = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B']
const FLAT_TO_SHARP: Record<string, string> = {
  Db: 'C#',
  Eb: 'D#',
  Gb: 'F#',
  Ab: 'G#',
  Bb: 'A#',
}

function createId(prefix: string) {
  return `${prefix}_${Math.random().toString(36).slice(2, 10)}`
}

function normalizeNote(note: string) {
  if (note in FLAT_TO_SHARP) {
    return FLAT_TO_SHARP[note]
  }

  return note
}

function transposeChord(symbol: string, semitones: number) {
  const trimmed = symbol.trim()
  if (!trimmed) {
    return symbol
  }

  const match = trimmed.match(/^([A-G](?:#|b)?)(.*)$/)
  if (!match) {
    return symbol
  }

  const [, root, suffix] = match
  const normalizedRoot = normalizeNote(root)
  const index = SHARP_NOTES.indexOf(normalizedRoot)

  if (index === -1) {
    return symbol
  }

  const shifted = (index + semitones + SHARP_NOTES.length * 4) % SHARP_NOTES.length
  return `${SHARP_NOTES[shifted]}${suffix}`
}

function buildFallbackChart(durationSec: number): GeneratedChart {
  const safeDuration = Math.max(40, Math.floor(durationSec) || 120)
  const lineLength = 8
  const lineCount = Math.max(4, Math.ceil(safeDuration / lineLength))

  const lines: LyricLine[] = Array.from({ length: lineCount }, (_, lineIndex) => {
    const startSec = lineIndex * lineLength
    const endSec = startSec + lineLength
    const rawWords = ['This', 'is', 'an', 'auto', 'generated', 'lyric', 'line', `${lineIndex + 1}`]
    const words = rawWords.map((word, wordIndex) => {
      const wordStart = startSec + (wordIndex / rawWords.length) * lineLength
      const nextStart = startSec + ((wordIndex + 1) / rawWords.length) * lineLength

      return {
        id: createId('word'),
        text: word,
        startSec: Number(wordStart.toFixed(2)),
        endSec: Number(Math.max(wordStart + 0.25, nextStart - 0.04).toFixed(2)),
      }
    })

    const chordPool = ['C', 'Am', 'F', 'G', 'Dm', 'Em']
    const chords: ChordSync[] = [0, 2, 4, 6].map((offset, idx) => ({
      id: createId('chord'),
      symbol: chordPool[(lineIndex + idx) % chordPool.length],
      timeSec: Number((startSec + offset).toFixed(2)),
    }))

    return {
      id: createId('line'),
      startSec,
      endSec,
      words,
      chords,
    }
  })

  return {
    lines,
    statusMessage: 'Auto-generated fallback chart ready. For production-grade results, connect a transcription/chord service endpoint.',
  }
}

async function decodeAudioDuration(audioContext: AudioContext, file: File) {
  const bytes = await file.arrayBuffer()
  const buffer = await audioContext.decodeAudioData(bytes.slice(0))
  return buffer.duration
}

async function requestAutoChart(primaryTrack: StudioTrack | null): Promise<GeneratedChart> {
  if (!primaryTrack) {
    return {
      lines: [],
      statusMessage: 'Upload a song first.',
    }
  }

  try {
    const response = await fetch('/api/autogen-chart', {
      method: 'POST',
      body: primaryTrack.file,
      headers: {
        'Content-Type': primaryTrack.file.type || 'audio/mpeg',
        'X-File-Name': encodeURIComponent(primaryTrack.name),
      },
    })

    if (response.ok) {
      const payload = (await response.json()) as { lines?: LyricLine[] }

      if (Array.isArray(payload.lines) && payload.lines.length > 0) {
        return {
          lines: payload.lines,
          statusMessage: 'Chart generated by connected AI service.',
        }
      }
    }
  } catch {
    // Ignore network failure and fallback.
  }

  return buildFallbackChart(primaryTrack.durationSec)
}

function SongStudioPage() {
  const audioContextRef = useRef<AudioContext | null>(null)
  const buffersRef = useRef<Map<string, AudioBuffer>>(new Map())
  const sourceNodesRef = useRef<NodeBundle[]>([])
  const rafRef = useRef<number | null>(null)
  const playStartedAtRef = useRef(0)
  const playOffsetRef = useRef(0)

  const [tracks, setTracks] = useState<StudioTrack[]>([])
  const [chartLines, setChartLines] = useState<LyricLine[]>([])
  const [isPlaying, setIsPlaying] = useState(false)
  const [currentTimeSec, setCurrentTimeSec] = useState(0)
  const [statusText, setStatusText] = useState('Upload a lead track and optional stems to start.')
  const [editMode, setEditMode] = useState(false)
  const [transposeSemitones, setTransposeSemitones] = useState(0)
  const [capo, setCapo] = useState(0)

  const leadTrack = tracks[0] ?? null
  const totalDurationSec = leadTrack?.durationSec ?? 0

  const currentLineIndex = useMemo(() => {
    if (chartLines.length === 0) {
      return -1
    }

    return chartLines.findIndex((line) => currentTimeSec >= line.startSec && currentTimeSec < line.endSec)
  }, [chartLines, currentTimeSec])

  const currentLine = currentLineIndex >= 0 ? chartLines[currentLineIndex] : null
  const nextLine = currentLineIndex >= 0 ? chartLines[currentLineIndex + 1] ?? null : chartLines[0] ?? null

  const displayedTranspose = transposeSemitones - capo

  const visibleChords = useMemo(() => {
    if (!currentLine) {
      return []
    }

    return currentLine.chords.map((chord) => ({
      ...chord,
      symbol: transposeChord(chord.symbol, displayedTranspose),
      isActive: currentTimeSec >= chord.timeSec && currentTimeSec < chord.timeSec + 1.2,
    }))
  }, [currentLine, currentTimeSec, displayedTranspose])

  const stopPlayback = () => {
    sourceNodesRef.current.forEach((bundle) => {
      try {
        bundle.source.stop()
      } catch {
        // Ignore stop races.
      }

      bundle.source.disconnect()
      bundle.gain.disconnect()
      bundle.panner.disconnect()
    })

    sourceNodesRef.current = []

    if (rafRef.current !== null) {
      window.cancelAnimationFrame(rafRef.current)
      rafRef.current = null
    }

    setIsPlaying(false)
  }

  useEffect(() => {
    return () => {
      stopPlayback()

      if (audioContextRef.current) {
        void audioContextRef.current.close()
      }

      tracks.forEach((track) => {
        URL.revokeObjectURL(track.objectUrl)
      })
    }
  }, [])

  const ensureAudioContext = () => {
    if (!audioContextRef.current) {
      audioContextRef.current = new AudioContext()
    }

    return audioContextRef.current
  }

  const onAddTrackFiles = async (fileList: FileList | null) => {
    if (!fileList || fileList.length === 0) {
      return
    }

    const acceptedFiles = Array.from(fileList).filter((file) => /audio\/(mpeg|wav|x-wav|mp3|aac|ogg)/i.test(file.type) || /\.(mp3|wav|aac|m4a|ogg)$/i.test(file.name))

    if (acceptedFiles.length === 0) {
      setStatusText('Only audio files (WAV/MP3/AAC/OGG) are supported.')
      return
    }

    const context = ensureAudioContext()
    const nextTracks: StudioTrack[] = []

    for (const file of acceptedFiles) {
      const durationSec = await decodeAudioDuration(context, file)
      const objectUrl = URL.createObjectURL(file)
      const id = createId('track')

      buffersRef.current.set(id, await context.decodeAudioData((await file.arrayBuffer()).slice(0)))

      nextTracks.push({
        id,
        name: file.name,
        file,
        objectUrl,
        durationSec,
        volume: 0.9,
        pan: 0,
        muted: false,
        solo: false,
      })
    }

    setTracks((current) => [...current, ...nextTracks])
    setStatusText(`${nextTracks.length} track(s) loaded. Run auto-generate to build lyric/chord sync.`)
  }

  const onGenerateChart = async () => {
    const chart = await requestAutoChart(leadTrack)
    setChartLines(chart.lines)
    setCurrentTimeSec(0)
    setStatusText(chart.statusMessage)
  }

  const syncTick = () => {
    const context = audioContextRef.current

    if (!context) {
      return
    }

    const elapsed = context.currentTime - playStartedAtRef.current
    const nextTime = Math.min(totalDurationSec || elapsed + playOffsetRef.current, playOffsetRef.current + elapsed)
    setCurrentTimeSec(nextTime)

    if (totalDurationSec > 0 && nextTime >= totalDurationSec) {
      playOffsetRef.current = 0
      setCurrentTimeSec(totalDurationSec)
      stopPlayback()
      return
    }

    rafRef.current = window.requestAnimationFrame(syncTick)
  }

  const startPlayback = async () => {
    if (tracks.length === 0) {
      setStatusText('Upload at least one audio file first.')
      return
    }

    const context = ensureAudioContext()
    await context.resume()

    stopPlayback()

    const hasSolo = tracks.some((track) => track.solo)

    sourceNodesRef.current = tracks.flatMap((track) => {
      const buffer = buffersRef.current.get(track.id)
      if (!buffer) {
        return []
      }

      const source = context.createBufferSource()
      source.buffer = buffer
      const gain = context.createGain()
      const panner = context.createStereoPanner()

      const trackAudible = hasSolo ? track.solo : !track.muted
      gain.gain.value = trackAudible ? track.volume : 0
      panner.pan.value = track.pan

      source.connect(gain)
      gain.connect(panner)
      panner.connect(context.destination)

      source.start(0, playOffsetRef.current)

      return [{ source, gain, panner }]
    })

    playStartedAtRef.current = context.currentTime
    setIsPlaying(true)
    rafRef.current = window.requestAnimationFrame(syncTick)
  }

  const onPausePlayback = () => {
    const context = audioContextRef.current
    if (!context) {
      return
    }

    const elapsed = context.currentTime - playStartedAtRef.current
    playOffsetRef.current = Math.min(totalDurationSec || elapsed + playOffsetRef.current, playOffsetRef.current + elapsed)
    stopPlayback()
  }

  const onSeek = (nextTimeSec: number) => {
    const bounded = Math.max(0, Math.min(totalDurationSec || 0, nextTimeSec))
    setCurrentTimeSec(bounded)
    playOffsetRef.current = bounded

    if (isPlaying) {
      void startPlayback()
    }
  }

  const updateTrack = (trackId: string, update: Partial<StudioTrack>) => {
    setTracks((current) => current.map((track) => (track.id === trackId ? { ...track, ...update } : track)))
  }

  const updateWordTiming = (lineId: string, wordId: string, patch: Partial<WordSync>) => {
    setChartLines((current) =>
      current.map((line) => {
        if (line.id !== lineId) {
          return line
        }

        return {
          ...line,
          words: line.words.map((word) => (word.id === wordId ? { ...word, ...patch } : word)),
        }
      }),
    )
  }

  const nudgeLine = (lineId: string, deltaSec: number) => {
    setChartLines((current) =>
      current.map((line) => {
        if (line.id !== lineId) {
          return line
        }

        return {
          ...line,
          startSec: Number((line.startSec + deltaSec).toFixed(2)),
          endSec: Number((line.endSec + deltaSec).toFixed(2)),
          words: line.words.map((word) => ({
            ...word,
            startSec: Number((word.startSec + deltaSec).toFixed(2)),
            endSec: Number((word.endSec + deltaSec).toFixed(2)),
          })),
          chords: line.chords.map((chord) => ({
            ...chord,
            timeSec: Number((chord.timeSec + deltaSec).toFixed(2)),
          })),
        }
      }),
    )
  }

  return (
    <section className="surface-card page-shell" aria-label="Song studio page">
      <header className="page-header">
        <p className="section-kicker">Song Studio</p>
        <h2>Upload audio, auto-generate chart, and perform with synced lyrics/chords</h2>
        <p>
          WAV/MP3 import, two-line karaoke flow, sync editor, capo + transpose, and stem mixer for backing tracks.
        </p>
      </header>

      <article className="studio-panel">
        <div className="studio-upload-row">
          <label className="studio-upload-btn" htmlFor="studio-audio-upload">Upload Lead/Stem Tracks</label>
          <input
            id="studio-audio-upload"
            type="file"
            accept="audio/*,.mp3,.wav,.aac,.m4a,.ogg"
            multiple
            onChange={(event) => {
              void onAddTrackFiles(event.target.files)
              event.currentTarget.value = ''
            }}
          />
          <button type="button" onClick={() => void onGenerateChart()}>Auto-Generate Lyrics + Chords</button>
          <button type="button" onClick={() => setEditMode((current) => !current)}>{editMode ? 'Exit Edit Mode' : 'Edit Sync'}</button>
        </div>
        <p className="studio-status">{statusText}</p>
      </article>

      <article className="studio-panel studio-transport">
        <div className="studio-transport-row">
          <button type="button" onClick={() => void startPlayback()} disabled={isPlaying}>Play</button>
          <button type="button" onClick={onPausePlayback} disabled={!isPlaying}>Pause</button>
          <button type="button" onClick={() => onSeek(0)}>Stop</button>
          <label>
            Capo
            <input type="number" min={0} max={12} value={capo} onChange={(event) => setCapo(Number(event.target.value) || 0)} />
          </label>
          <label>
            Transpose
            <input type="number" min={-6} max={6} value={transposeSemitones} onChange={(event) => setTransposeSemitones(Number(event.target.value) || 0)} />
          </label>
        </div>
        <label className="studio-seek">
          <span>{currentTimeSec.toFixed(2)}s / {totalDurationSec.toFixed(2)}s</span>
          <input
            type="range"
            min={0}
            max={Math.max(1, totalDurationSec)}
            step={0.01}
            value={Math.min(currentTimeSec, Math.max(1, totalDurationSec))}
            onChange={(event) => onSeek(Number(event.target.value))}
          />
        </label>
      </article>

      <article className="studio-panel studio-karaoke">
        <p className="panel-label">Live Lyric + Chord View</p>
        <div className="studio-chord-row" role="list" aria-label="Current line chords">
          {visibleChords.map((chord) => (
            <p key={chord.id} role="listitem" className={chord.isActive ? 'studio-chord-active' : ''}>{chord.symbol}</p>
          ))}
        </div>

        <div className="studio-current-line" aria-label="Current lyric line">
          {(currentLine?.words ?? []).map((word) => {
            const active = currentTimeSec >= word.startSec && currentTimeSec < word.endSec
            return (
              <span key={word.id} className={active ? 'studio-word-active' : ''}>{word.text}</span>
            )
          })}
          {!currentLine ? <span className="studio-placeholder">Current line will appear during playback.</span> : null}
        </div>

        <div className="studio-next-line" aria-label="Next lyric line">
          {(nextLine?.words ?? []).map((word) => (
            <span key={word.id}>{word.text}</span>
          ))}
          {!nextLine ? <span className="studio-placeholder">Next line preview appears here.</span> : null}
        </div>
      </article>

      <article className="studio-panel">
        <p className="panel-label">Stem Mixer</p>
        <div className="studio-track-list" role="list" aria-label="Audio tracks">
          {tracks.map((track) => (
            <div key={track.id} className="studio-track-row" role="listitem">
              <p>{track.name}</p>
              <label>
                Vol
                <input type="range" min={0} max={1} step={0.01} value={track.volume} onChange={(event) => updateTrack(track.id, { volume: Number(event.target.value) })} />
              </label>
              <label>
                Pan
                <input type="range" min={-1} max={1} step={0.01} value={track.pan} onChange={(event) => updateTrack(track.id, { pan: Number(event.target.value) })} />
              </label>
              <button type="button" onClick={() => updateTrack(track.id, { muted: !track.muted })}>{track.muted ? 'Unmute' : 'Mute'}</button>
              <button type="button" onClick={() => updateTrack(track.id, { solo: !track.solo })}>{track.solo ? 'Unsolo' : 'Solo'}</button>
            </div>
          ))}
          {tracks.length === 0 ? <p className="studio-status">No tracks loaded yet.</p> : null}
        </div>
      </article>

      {editMode ? (
        <article className="studio-panel">
          <p className="panel-label">Sync Edit Mode</p>
          <div className="studio-edit-list" role="list" aria-label="Sync lines">
            {chartLines.map((line) => (
              <div key={line.id} role="listitem" className="studio-edit-line">
                <div className="studio-edit-line-head">
                  <p>{line.words.map((word) => word.text).join(' ')}</p>
                  <div>
                    <button type="button" onClick={() => nudgeLine(line.id, -0.1)}>Nudge -0.1s</button>
                    <button type="button" onClick={() => nudgeLine(line.id, 0.1)}>Nudge +0.1s</button>
                  </div>
                </div>
                <div className="studio-edit-word-grid">
                  {line.words.map((word) => (
                    <label key={word.id}>
                      {word.text}
                      <div>
                        <input
                          type="number"
                          step={0.01}
                          value={word.startSec}
                          onChange={(event) => updateWordTiming(line.id, word.id, { startSec: Number(event.target.value) })}
                        />
                        <input
                          type="number"
                          step={0.01}
                          value={word.endSec}
                          onChange={(event) => updateWordTiming(line.id, word.id, { endSec: Number(event.target.value) })}
                        />
                      </div>
                    </label>
                  ))}
                </div>
              </div>
            ))}
            {chartLines.length === 0 ? <p className="studio-status">Generate a chart to edit sync.</p> : null}
          </div>
        </article>
      ) : null}
    </section>
  )
}

export default SongStudioPage
