export type DefaultSetlistSong = {
  title: string
  artist: string
  isExplicit?: boolean
}

export const DEFAULT_SETLIST_SONGS: DefaultSetlistSong[] = [
  { title: 'Have You Ever Seen the Rain', artist: 'Creedence Clearwater Revival' },
  { title: 'Stand by Me', artist: 'Ben E. King' },
  { title: 'Take Me Home, Country Roads', artist: 'John Denver' },
  { title: 'Let It Be', artist: 'The Beatles' },
  { title: 'Losing My Religion', artist: 'R.E.M.' },
  { title: 'Wonderwall', artist: 'Oasis' },
  { title: 'Shallow', artist: 'A Star is Born (2018 film) (Lady Gaga & Bradley Cooper)' },
  { title: 'Jolene', artist: 'Dolly Parton' },
  { title: 'Heart of Gold', artist: 'Neil Young' },
  { title: 'Boulevard of Broken Dreams', artist: 'Green Day' },
  { title: 'One', artist: 'U2' },
  { title: 'Space Oddity', artist: 'David Bowie' },
  { title: 'Budapest', artist: 'George Ezra' },
  { title: 'Hurt', artist: 'Johnny Cash' },
  { title: 'The Man Who Sold the World', artist: 'Nirvana' },
  { title: 'Sweet Caroline', artist: 'Neil Diamond' },
  { title: 'Zombie', artist: 'The Cranberries' },
  { title: 'Take Me Home, Country Roads', artist: 'John Denver' },
  { title: 'Wicked Game', artist: 'Chris Isaak' },
  { title: 'Creep (acoustic)', artist: 'Radiohead' },
  { title: "What's Up? (acoustic)", artist: '4 Non Blondes' },
  { title: 'Zombie (acoustic)', artist: 'The Cranberries' },
  { title: "Don't Look Back in Anger (acoustic - live MTV Unplugged)", artist: 'Oasis' },
  { title: 'Set Fire to the Rain (acoustic)', artist: 'Adele' },
  { title: "Who'll Stop the Rain", artist: 'John Fogerty' },
  { title: 'The Wild Rover', artist: 'The Dubliners' },
  { title: 'Whiskey in the Jar (live)', artist: 'Mike Denver' },
  { title: 'For No One', artist: 'The Beatles' },
  { title: 'Nowhere Man', artist: 'The Beatles' },
  { title: 'Make Me Smile (Come Up And See Me)', artist: 'Steve Harley And Cockney Rebel' },
  { title: 'The Streets of London', artist: 'Mike Denver' },
  { title: '50 Ways to Leave Your Lover (shorter version)', artist: 'Paul Simon' },
  { title: "Fisherman's Blues", artist: 'The Waterboys' },
  { title: 'Get Back', artist: 'The Beatles' },
  { title: 'I Will', artist: 'The Beatles' },
  { title: 'Here, There and Everywhere', artist: 'The Beatles' },
  { title: 'The Gambler', artist: 'Kenny Rogers' },
  { title: 'Take It Easy', artist: 'Jackson Browne' },
  { title: 'Tulsa Time', artist: 'Pistol Annies' },
  { title: 'Times Like These', artist: 'Glen Campbell' },
  { title: 'Against the Wind', artist: 'Bob Seger' },
  { title: 'Turn the Page', artist: 'Bob Seger' },
  { title: 'Take It to the Limit (live)', artist: 'Eagles' },
  { title: 'Peaceful Easy Feeling (live)', artist: 'Johnny Brady' },
  { title: 'Walk of Life (live)', artist: 'Mike Denver (The Late Late Country Special)' },
  { title: 'Lemon Tree', artist: "Fool's Garden" },
  { title: 'Something to Talk About', artist: 'Bonnie Raitt' },
  { title: 'Summer of ‘69 (Little More Country Sessions)', artist: 'Max Jackson' },
  { title: 'Heroes (live)', artist: 'David Bowie' },
  { title: 'Absolute Beginners', artist: 'David Bowie' },
  { title: "Fishin' in the Dark", artist: 'Nitty Gritty Dirt Band' },
  { title: 'Blowing in the Wind', artist: 'Mike Denver' },
  { title: 'Seasons in the Sun', artist: 'Mike Denver' },
  { title: 'Sister Golden Hair', artist: 'America' },
  { title: 'Achy Breaky Heart', artist: 'Billy Ray Cyrus' },
  { title: 'One More Cup of Coffee (Valley Below)', artist: 'Bob Dylan' },
  { title: 'The River', artist: 'Bruce Springsteen' },
  { title: 'Yellow', artist: 'Coldplay' },
  { title: 'Proud Mary', artist: 'Creedence Clearwater Revival' },
  { title: 'Lodi', artist: 'Creedence Clearwater Revival' },
  { title: 'Tie a Yellow Ribbon Round the Ole Oak Tree', artist: 'Dean Martin' },
  { title: 'Blue Moon of Kentucky', artist: 'Dwight Yoakam' },
  { title: "Drivin' My Life Away", artist: 'Eddie Rabbitt' },
  { title: "Gimme Hope Jo'anna", artist: 'Eddy Grant' },
  { title: 'Burning Love', artist: 'Elvis Presley' },
  { title: 'Knock on Wood', artist: 'Eric Clapton' },
  { title: 'Alberta (live Acoustic version)', artist: 'Eric Clapton' },
  { title: 'The Way', artist: 'Fastball' },
  { title: 'Blame It on Me', artist: 'George Ezra' },
  { title: 'My Sweet Lord', artist: 'George Harrison' },
  { title: 'All Things Must Pass', artist: 'George Harrison' },
  { title: 'Amarillo by Morning', artist: 'George Strait' },
  { title: 'Jealous Guy', artist: 'John Lennon' },
  { title: 'Så længe jeg lever', artist: 'John Mogensen' },
  { title: 'The Gambler', artist: 'Johnny Brady' },
  { title: 'Joanna', artist: 'Kim Larsen' },
  { title: 'Midt om natten', artist: 'Kim Larsen' },
  { title: 'The Cave', artist: 'Mumford & Sons' },
  { title: 'Polly', artist: 'Nirvana' },
  { title: 'Stop Crying Your Heart Out', artist: 'Oasis' },
  { title: 'Half the World Away', artist: 'Oasis' },
  { title: 'Stand by Me', artist: 'Oasis' },
  { title: 'Man on the Moon', artist: 'R.E.M.' },
  { title: 'Karma Police', artist: 'Radiohead' },
  { title: 'Something Beautiful', artist: 'Robbie Williams' },
  { title: "She's The One", artist: 'Robbie Williams' },
  { title: 'Angels (acoustic)', artist: 'Robbie Williams' },
  { title: 'When You Say Nothing at All', artist: 'Ronan Keating' },
  { title: 'If Tomorrow Never Comes', artist: 'Ronan Keating' },
  { title: 'Make You Feel My Love', artist: 'Ronan Keating' },
  { title: 'Father and Son', artist: 'Ronan Keating & Cat Stevens' },
  { title: 'You Got It', artist: 'Roy Orbison' },
  { title: 'Living Next Door to Alice', artist: 'Smokie' },
  { title: 'Blinding Lights (country version)', artist: 'Tebey' },
  { title: "When I'm Sixty-Four", artist: 'The Beatles' },
  { title: "You've Got to Hide Your Love Away", artist: 'The Beatles' },
  { title: 'All My Loving', artist: 'The Beatles' },
  { title: 'Girl', artist: 'The Beatles' },
  { title: 'A Taste of Honey', artist: 'The Beatles' },
  { title: 'Two of Us', artist: 'The Beatles' },
  { title: 'Let Your Love Flow', artist: 'The Bellamy Brothers' },
  { title: "'74 '75", artist: 'The Connells' },
  { title: 'I Got Stripes / Folsom Prison Blues / Ring of Fire', artist: 'The Three Amigos' },
  { title: 'Happy Together', artist: 'The Turtles' },
  { title: "Mary Jane's Last Dance", artist: 'Tom Petty' },
  { title: "I Hope That I Don't Fall in Love with You", artist: 'Tom Waits' },
  { title: 'On the Road Again', artist: 'Willie Nelson' },
]