/**
 * Fake event data for Demo Mode.
 * Mirrors the EventState shape used by queueStore.
 */
export const DEMO_EVENT = {
  id: 'demo-event-001',
  hostId: 'c44e0b72-1b31-44ca-a31d-05922d4d939d',
  name: 'The Groove Lounge — Live Night',
  venue: 'The Groove Lounge',
  gigDate: new Date().toISOString().split('T')[0],
  gigStartTime: '20:00',
  gigEndTime: '23:30',
  subtitle: 'Your requests keep the party alive 🎶',
  requestInstructions: 'Type a song and artist, then hit Add to Queue!',
  instagramUrl: 'https://instagram.com/thehumanjukebox',
  tiktokUrl: 'https://tiktok.com/@thehumanjukebox',
  youtubeUrl: 'https://youtube.com/@thehumanjukebox',
  facebookUrl: 'https://facebook.com/thehumanjukebox',
  paypalUrl: 'https://paypal.me/demohost',
  mobilpayUrl: null,
  contactEmail: 'booking@the-human-jukebox.org',
  playlistOnlyRequests: false,
  mirrorPhotoSpotlightEnabled: true,
  mirrorCountdownEnabled: false,
  mirrorCountdownShowQrLink: true,
  mirrorCountdownQrLink: null,
  mirrorCountdownQrCustomEnabled: false,
  mirrorCountdownQrCustomUrl: null,
  mirrorCountdownQrText: null,
  mirrorCountdownQrFlashEnabled: true,
  mirrorCountdownQrFlashVenue: 'The Groove Lounge',
  mirrorBreakQrEnabled: false,
  mirrorBreakQrCustomUrl: null,
  mirrorBannerEnabled: true,
  mirrorBannerText: 'Welcome legends - requests are open all night!',
  allowDuplicateRequests: false,
  maxActiveRequestsPerUser: 2,
  maxQueueSize: 30,
  roomOpen: true,
  explicitFilterEnabled: false,
  showInAudienceNoGig: false,
  coverImageUrl: '/the-human-jukebox-logo.png',
  venueLogoUrl: null,
  venueLogoScale: 100,
  venueLogoOffsetX: 0,
  venueLogoOffsetY: 0,
  venueLogoAppearance: 'clean',
  showCustomButton: false,
  customButtonLabel: null,
  customButtonLink: null,
  tipThankYouMessageDA: 'Tak for dit tip! 🙏',
  tipThankYouMessageEN: 'Thanks for the tip! 🙏',
  eventType: 'halli-live',
  eventTheme: 'human-jukebox',
  karafunUrl: null,
  artistName: null,
  audienceVotingEnabled: true,
  audienceIcelandicEnabled: false,
  autoLiveEnabled: false,
  introAudioUrl: null,
  isTestGig: false,
} as const
