import type { QueueSong } from '../state/queueStore'

/**
 * Initial fake queue for Demo Mode.
 * Contains 8 realistic requests that a bar audience might submit.
 */
export const DEMO_INITIAL_QUEUE: QueueSong[] = [
  {
    id: 'demo-song-001',
    event_id: 'demo-event-001',
    title: 'Africa',
    artist: 'Toto',
    votes_count: 7,
    is_explicit: false,
    voting_locked: false,
    is_removed: false,
    cover_url: null,
    library_song_id: null,
    audience_sings: false,
    position: 1,
    createdByName: 'Maria K.',
  },
  {
    id: 'demo-song-002',
    event_id: 'demo-event-001',
    title: 'Sweet Caroline',
    artist: 'Neil Diamond',
    votes_count: 5,
    is_explicit: false,
    voting_locked: false,
    is_removed: false,
    cover_url: null,
    library_song_id: null,
    audience_sings: false,
    position: 2,
    createdByName: 'Thomas B.',
  },
  {
    id: 'demo-song-003',
    event_id: 'demo-event-001',
    title: 'Mr. Brightside',
    artist: 'The Killers',
    votes_count: 4,
    is_explicit: false,
    voting_locked: false,
    is_removed: false,
    cover_url: null,
    library_song_id: null,
    audience_sings: false,
    position: 3,
    createdByName: 'Sophie L.',
  },
  {
    id: 'demo-song-004',
    event_id: 'demo-event-001',
    title: 'Don\'t Stop Believin\'',
    artist: 'Journey',
    votes_count: 3,
    is_explicit: false,
    voting_locked: false,
    is_removed: false,
    cover_url: null,
    library_song_id: null,
    audience_sings: false,
    position: 4,
    createdByName: 'Lars M.',
  },
  {
    id: 'demo-song-005',
    event_id: 'demo-event-001',
    title: 'Livin\' on a Prayer',
    artist: 'Bon Jovi',
    votes_count: 2,
    is_explicit: false,
    voting_locked: false,
    is_removed: false,
    cover_url: null,
    library_song_id: null,
    audience_sings: false,
    position: 5,
    createdByName: 'Ida H.',
  },
  {
    id: 'demo-song-006',
    event_id: 'demo-event-001',
    title: 'Bohemian Rhapsody',
    artist: 'Queen',
    votes_count: 2,
    is_explicit: false,
    voting_locked: false,
    is_removed: false,
    cover_url: null,
    library_song_id: null,
    audience_sings: false,
    position: 6,
    createdByName: 'Frederik P.',
  },
  {
    id: 'demo-song-007',
    event_id: 'demo-event-001',
    title: 'Dancing Queen',
    artist: 'ABBA',
    votes_count: 1,
    is_explicit: false,
    voting_locked: false,
    is_removed: false,
    cover_url: null,
    library_song_id: null,
    audience_sings: false,
    position: 7,
    createdByName: 'Anna C.',
  },
  {
    id: 'demo-song-008',
    event_id: 'demo-event-001',
    title: 'Wonderwall',
    artist: 'Oasis',
    votes_count: 0,
    is_explicit: false,
    voting_locked: false,
    is_removed: false,
    cover_url: null,
    library_song_id: null,
    audience_sings: false,
    position: 8,
    createdByName: 'Demo User',
  },
]
